---
name: Salt Kitchen test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kitchen-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instances:
          - default-ubuntu-2204-30069
          - default-ubuntu-2404-30069
          - default-ubuntu-2204-30071
          - default-ubuntu-2404-30071
          - default-debian-12-30069
          - default-debian-12-30071
          - default-rocky9-30069
          - default-rocky9-30071
          - default-fedora40-30069
          - default-fedora40-30071
          #- default-opensuse15-30060 / symlink of docker formula not resolved ... can't test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Add hashicorp source
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
      - name: Install vagrant and virtualbox
        uses: ConorMacBride/install-package@v1
        with:
          apt: vagrant virtualbox
      - name: Run kitchen test
        run: |
          CRED="export HETZNER_TOKEN=${{ secrets.HETZNER_TOKEN }}" bundle exec kitchen test ${{ matrix.instances }}
